package com.wuspace.domain;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.created_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.updated_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.deleted_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.category
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.tags
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.viewed_times
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long viewedTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long zanUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long caiUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.created_at
     *
     * @return the value of blog.created_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.created_at
     *
     * @param createdAt the value for blog.created_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.updated_at
     *
     * @return the value of blog.updated_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.updated_at
     *
     * @param updatedAt the value for blog.updated_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.deleted_at
     *
     * @return the value of blog.deleted_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.deleted_at
     *
     * @param deletedAt the value for blog.deleted_at
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.user_id
     *
     * @return the value of blog.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.user_id
     *
     * @param userId the value for blog.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.category
     *
     * @return the value of blog.category
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.category
     *
     * @param category the value for blog.category
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.tags
     *
     * @return the value of blog.tags
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.tags
     *
     * @param tags the value for blog.tags
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.viewed_times
     *
     * @return the value of blog.viewed_times
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getViewedTimes() {
        return viewedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.viewed_times
     *
     * @param viewedTimes the value for blog.viewed_times
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setViewedTimes(Long viewedTimes) {
        this.viewedTimes = viewedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.zan_user_id
     *
     * @return the value of blog.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getZanUserId() {
        return zanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.zan_user_id
     *
     * @param zanUserId the value for blog.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setZanUserId(Long zanUserId) {
        this.zanUserId = zanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.cai_user_id
     *
     * @return the value of blog.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getCaiUserId() {
        return caiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.cai_user_id
     *
     * @param caiUserId the value for blog.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setCaiUserId(Long caiUserId) {
        this.caiUserId = caiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}