package com.wuspace.domain;

import java.util.ArrayList;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdIsNull() {
            addCriterion("on_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOnUserIdIsNotNull() {
            addCriterion("on_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOnUserIdEqualTo(Long value) {
            addCriterion("on_user_id =", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdNotEqualTo(Long value) {
            addCriterion("on_user_id <>", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdGreaterThan(Long value) {
            addCriterion("on_user_id >", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("on_user_id >=", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdLessThan(Long value) {
            addCriterion("on_user_id <", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdLessThanOrEqualTo(Long value) {
            addCriterion("on_user_id <=", value, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdIn(List<Long> values) {
            addCriterion("on_user_id in", values, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdNotIn(List<Long> values) {
            addCriterion("on_user_id not in", values, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdBetween(Long value1, Long value2) {
            addCriterion("on_user_id between", value1, value2, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnUserIdNotBetween(Long value1, Long value2) {
            addCriterion("on_user_id not between", value1, value2, "onUserId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdIsNull() {
            addCriterion("on_blog_id is null");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdIsNotNull() {
            addCriterion("on_blog_id is not null");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdEqualTo(Long value) {
            addCriterion("on_blog_id =", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdNotEqualTo(Long value) {
            addCriterion("on_blog_id <>", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdGreaterThan(Long value) {
            addCriterion("on_blog_id >", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("on_blog_id >=", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdLessThan(Long value) {
            addCriterion("on_blog_id <", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdLessThanOrEqualTo(Long value) {
            addCriterion("on_blog_id <=", value, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdIn(List<Long> values) {
            addCriterion("on_blog_id in", values, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdNotIn(List<Long> values) {
            addCriterion("on_blog_id not in", values, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdBetween(Long value1, Long value2) {
            addCriterion("on_blog_id between", value1, value2, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andOnBlogIdNotBetween(Long value1, Long value2) {
            addCriterion("on_blog_id not between", value1, value2, "onBlogId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdIsNull() {
            addCriterion("zan_user_id is null");
            return (Criteria) this;
        }

        public Criteria andZanUserIdIsNotNull() {
            addCriterion("zan_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andZanUserIdEqualTo(Long value) {
            addCriterion("zan_user_id =", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdNotEqualTo(Long value) {
            addCriterion("zan_user_id <>", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdGreaterThan(Long value) {
            addCriterion("zan_user_id >", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("zan_user_id >=", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdLessThan(Long value) {
            addCriterion("zan_user_id <", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdLessThanOrEqualTo(Long value) {
            addCriterion("zan_user_id <=", value, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdIn(List<Long> values) {
            addCriterion("zan_user_id in", values, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdNotIn(List<Long> values) {
            addCriterion("zan_user_id not in", values, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdBetween(Long value1, Long value2) {
            addCriterion("zan_user_id between", value1, value2, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andZanUserIdNotBetween(Long value1, Long value2) {
            addCriterion("zan_user_id not between", value1, value2, "zanUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdIsNull() {
            addCriterion("cai_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdIsNotNull() {
            addCriterion("cai_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdEqualTo(Long value) {
            addCriterion("cai_user_id =", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdNotEqualTo(Long value) {
            addCriterion("cai_user_id <>", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdGreaterThan(Long value) {
            addCriterion("cai_user_id >", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("cai_user_id >=", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdLessThan(Long value) {
            addCriterion("cai_user_id <", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdLessThanOrEqualTo(Long value) {
            addCriterion("cai_user_id <=", value, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdIn(List<Long> values) {
            addCriterion("cai_user_id in", values, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdNotIn(List<Long> values) {
            addCriterion("cai_user_id not in", values, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdBetween(Long value1, Long value2) {
            addCriterion("cai_user_id between", value1, value2, "caiUserId");
            return (Criteria) this;
        }

        public Criteria andCaiUserIdNotBetween(Long value1, Long value2) {
            addCriterion("cai_user_id not between", value1, value2, "caiUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 08 23:02:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}