package com.wuspace.domain;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.on_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long onUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.on_blog_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long onBlogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long zanUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long caiUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.on_user_id
     *
     * @return the value of comment.on_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getOnUserId() {
        return onUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.on_user_id
     *
     * @param onUserId the value for comment.on_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setOnUserId(Long onUserId) {
        this.onUserId = onUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.on_blog_id
     *
     * @return the value of comment.on_blog_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getOnBlogId() {
        return onBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.on_blog_id
     *
     * @param onBlogId the value for comment.on_blog_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setOnBlogId(Long onBlogId) {
        this.onBlogId = onBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.zan_user_id
     *
     * @return the value of comment.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getZanUserId() {
        return zanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.zan_user_id
     *
     * @param zanUserId the value for comment.zan_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setZanUserId(Long zanUserId) {
        this.zanUserId = zanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cai_user_id
     *
     * @return the value of comment.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getCaiUserId() {
        return caiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cai_user_id
     *
     * @param caiUserId the value for comment.cai_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setCaiUserId(Long caiUserId) {
        this.caiUserId = caiUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}