package com.wuspace.domain;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}