package com.wuspace.domain;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.to_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.to_comment_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Long toCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.user_id
     *
     * @return the value of reply.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.user_id
     *
     * @param userId the value for reply.user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.to_user_id
     *
     * @return the value of reply.to_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.to_user_id
     *
     * @param toUserId the value for reply.to_user_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.to_comment_id
     *
     * @return the value of reply.to_comment_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Long getToCommentId() {
        return toCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.to_comment_id
     *
     * @param toCommentId the value for reply.to_comment_id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setToCommentId(Long toCommentId) {
        this.toCommentId = toCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}