package com.wuspace.domain;

public class TopicType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_type.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_type.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_type.description
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_type.id
     *
     * @return the value of topic_type.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_type.id
     *
     * @param id the value for topic_type.id
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_type.name
     *
     * @return the value of topic_type.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_type.name
     *
     * @param name the value for topic_type.name
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_type.description
     *
     * @return the value of topic_type.description
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_type.description
     *
     * @param description the value for topic_type.description
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}