package com.wuspace.dao;

import com.wuspace.domain.TopicType;
import com.wuspace.domain.TopicTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    long countByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    int deleteByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    int insert(TopicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    int insertSelective(TopicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    List<TopicType> selectByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicType record, @Param("example") TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_type
     *
     * @mbg.generated Thu Jun 08 23:02:10 CST 2017
     */
    int updateByExample(@Param("record") TopicType record, @Param("example") TopicTypeExample example);
}