
spring:
    application:
        name: news
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev
    jackson:
        serialization.write_dates_as_timestamps: false
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
        static-path-pattern: /**
    resources:
        static-locations: /, /content/images/, file:${fileLoad.img_path}, file:${fileLoad.filePath}
    thymeleaf:
        mode: HTML

